[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/models/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/models/*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"
